setwd("~/Downloads")
red_wine <- read.csv(file = "winequality-red(1).csv", header = TRUE, sep=";")
data_red <- head(red_wine)
print(data_red)
View(red_wine)
plot(red_wine[,2:4])
plot(data_red[,2:4])
white_wine <- read.csv(file = "winequality-white(1).csv", header = TRUE, sep=";")
data_white <- head(white_wine)
print(data_white)
View(white_wine)
plot(white_wine[,2:4])
plot(data_white[,2:4])
plot(data_red[,2:4])
plot(data_white[,4:6])